### ISSUE TITLE
DEvis installation issue

### ISSUE THREAD

**Issue by ghost** [price0416/DEvis#3]
Tried both installing via CRAN and Github. Neither option worked. Any ideas? Thanks!

**Comment by price0416** [comment]
Can you provide any more details? Error messages/version numbers?

What happens when you try to install it with devtools install?

**Comment by ghost** [comment]
Sure. 
Thanks a lot for your answer and sorry for the lack of details.

#####
> devtools::install_github("price0416/DEvis/DEvis")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`price0416`) and repo name (`DEvis`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
#####

It seems that it's not finding the repo...

Version information:

#####
$ R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
#####

Trying CRAN:

#####
> install.packages("DEVis")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘DEVis’ is not available (for R version 3.6.3)
####

Is DEVis only available for R4?

Thanks

**Comment by price0416** [comment]
Try with devtools::install_github("price0416/DEvis/DEVis")

It's possible there is an issue with the capitalization of the V.  As for the version number, it should be reverse compatible.  Let me know if that doesn't work.  I am still using it myself personally and though I see the version warning numbers it doesn't effect the usage of the package.  Sometime soon I'll try to address the dependency issue that is keeping it off CRAN as well.  Sorry for the trouble.

**Comment by ghost** [comment]
The devtools method worked. 
The V capitalization did the trick! I completely missed it. 
Thanks a lot Adam for the troubleshooting.
Best
